
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Info, FileEdit, Share } from 'lucide-react';

interface ActionPoint {
  id: string;
  content: string;
  assignee: string;
}

interface ActionPointsProps {
  actionPoints: ActionPoint[];
  onEdit: () => void;
  onShare: () => void;
}

const ActionPoints: React.FC<ActionPointsProps> = ({
  actionPoints,
  onEdit,
  onShare
}) => {
  // Group action points by assignee
  const groupedPoints = actionPoints.reduce((acc, point) => {
    if (!acc[point.assignee]) {
      acc[point.assignee] = [];
    }
    acc[point.assignee].push(point);
    return acc;
  }, {} as Record<string, ActionPoint[]>);

  return (
    <Card className="h-full">
      <CardContent className="p-6">
        <div className="flex items-center text-sm text-gray-500 mb-4">
          <Info className="h-4 w-4 mr-2" />
          <span>Generated by AI. Check for accuracy.</span>
        </div>

        <div className="space-y-6 mb-6">
          {Object.entries(groupedPoints).map(([assignee, points]) => (
            <div key={assignee}>
              <h3 className="font-semibold text-lg mb-3">Action points for {assignee}</h3>
              <ol className="list-decimal pl-5 space-y-2">
                {points.map((point) => (
                  <li key={point.id} className="pl-1">
                    <p>{point.content}</p>
                  </li>
                ))}
              </ol>
            </div>
          ))}
        </div>

        <div className="flex space-x-3">
          <Button variant="outline" onClick={onEdit}>
            <FileEdit className="h-4 w-4 mr-2" />
            Edit action points
          </Button>
          <Button onClick={onShare}>
            <Share className="h-4 w-4 mr-2" />
            Share with client
          </Button>
        </div>
      </CardContent>
    </Card>
  );
};

export default ActionPoints;
