
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Info, FileEdit, BookOpen } from 'lucide-react';

interface LearningCategory {
  id: string;
  title: string;
  points: string[];
}

interface LearningPointsProps {
  categories: LearningCategory[];
  onEdit: () => void;
  onOpenKnowledgeCenter: () => void;
}

const LearningPoints: React.FC<LearningPointsProps> = ({
  categories,
  onEdit,
  onOpenKnowledgeCenter
}) => {
  return (
    <div className="max-w-5xl mx-auto">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center text-sm text-gray-500">
          <Info className="h-4 w-4 mr-2" />
          <span>Generated by AI. Check for accuracy.</span>
        </div>
      </div>

      <div className="bg-white rounded-lg p-8 shadow-sm">
        {categories.map((category, index) => (
          <div key={category.id}>
            <h3 className="font-semibold text-lg mb-3">{index + 1}. {category.title}</h3>
            <ul className="list-disc pl-5 space-y-2">
              {category.points.map((point, idx) => (
                <li key={idx} className="pl-1">
                  <p>{point}</p>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
};

export default LearningPoints;
