
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Info, FileEdit, BookOpen } from 'lucide-react';

interface LearningCategory {
  id: string;
  title: string;
  points: string[];
}

interface LearningPointsProps {
  categories: LearningCategory[];
  onEdit: () => void;
  onOpenKnowledgeCenter: () => void;
}

const LearningPoints: React.FC<LearningPointsProps> = ({
  categories,
  onEdit,
  onOpenKnowledgeCenter
}) => {
  return (
    <div className="max-w-5xl mx-auto">
      <div className="bg-white shadow-sm flex items-center justify-between mb-1">
        <div className="flex items-center p-5 text-sm text-gray-500">
          <Info
            className="h-4 w-4 mr-2"
            color="#1B1464"
            style={{ color: '#1B1464', stroke: 'red' }}
          />
          <span>Generated by AI. Check for accuracy.</span>
        </div>
      </div>

      <div className="bg-white rounded-lg p-8 shadow-sm">
        {categories.map((category, index) => (
          <div key={category.id}>
            <h3 className="text-[#1B1464] text-[18px] font-[600] mb-2" style={{ marginTop: index > 0 ? '2.5rem' : 0 }}>
              {index + 1}. {category.title}
            </h3>
            <ul className="mb-4">
              {category.points.map((point, idx) => (
                <li key={idx} className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">
                  <p>{point}</p>
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
    </div>
  );
};

export default LearningPoints;
