
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Info, FileEdit, BookOpen } from 'lucide-react';

interface LearningCategory {
  id: string;
  title: string;
  points: string[];
}

interface LearningPointsProps {
  categories: LearningCategory[];
  onEdit: () => void;
  onOpenKnowledgeCenter: () => void;
}

const LearningPoints: React.FC<LearningPointsProps> = ({
  categories,
  onEdit,
  onOpenKnowledgeCenter
}) => {
  return (
    <Card className="h-full">
      <CardContent className="p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center text-sm text-gray-500">
            <Info className="h-4 w-4 mr-2" />
            <span>Generated by AI. Check for accuracy.</span>
          </div>
          <div className="flex space-x-3">
            <Button variant="outline" onClick={onEdit}>
              <FileEdit className="h-4 w-4 mr-2" />
              Edit learning points
            </Button>
            <Button onClick={onOpenKnowledgeCenter}>
              <BookOpen className="h-4 w-4 mr-2" />
              Open knowledge center
            </Button>
          </div>
        </div>

        <div className="space-y-6 mb-6">
          {categories.map((category, index) => (
            <div key={category.id}>
              <h3 className="font-semibold text-lg mb-3">{index + 1}. {category.title}</h3>
              <ul className="list-disc pl-5 space-y-2">
                {category.points.map((point, idx) => (
                  <li key={idx} className="pl-1">
                    <p>{point}</p>
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </CardContent>
    </Card>
  );
};

export default LearningPoints;
