
import React from 'react';
import { Button } from '@/components/ui/button';
import { Info, FileEdit, Share } from 'lucide-react';
import { cn } from '@/lib/utils';

interface SummaryContentProps {
  content: string;
  onEdit: () => void;
  onShare: () => void;
}

const SummaryContent: React.FC<SummaryContentProps> = ({
  content,
  onEdit,
  onShare
}) => {
  return (
    <div className="max-w-5xl mx-auto">
      <div className="bg-white shadow-sm flex items-center justify-between mb-1">
        <div className="flex items-center p-5 text-sm text-gray-500">
          <Info
            className="h-4 w-4 mr-2"
            color="#ea384c"  // Using the red color from the project's color palette
            strokeWidth={2}
          />
          <span>Generated by AI. Check for accuracy.</span>
        </div>
      </div>

      <div className="bg-white p-8 shadow-sm">
        <div className="flex justify-between items-start mb-6">
          <div>
            <h4 className="text-xl font-semibold text-gray-900 mb-2">Links</h4>
            <div className="space-y-2 flex flex-col">
              <a href="#" className="text-[#1B1464] hover:underline flex items-center">
                <span className="mr-2">1</span>
                Equipment breakdown insurance.pdf
              </a>
              <a href="#" className="text-[#1B1464] hover:underline flex items-center">
                <span className="mr-2">2</span>
                Business interruption insurance.pdf
              </a>
            </div>
          </div>
        </div>

        <div
          // className={cn(
          //   'prose max-w-none',
          //   'prose-h2:text-2xl prose-h2:font-bold prose-h2:text-gray-900 prose-h2:mb-6',
          //   'prose-h4:text-lg prose-h4:font-semibold prose-h4:text-gray-900 prose-h4:mt-8 prose-h4:mb-4',
          //   'prose-p:text-gray-600 prose-p:leading-relaxed',
          //   'prose-ul:list-disc prose-ul:pl-6 prose-ul:space-y-2',
          //   'prose-li:text-gray-600'
          // )}
          // dangerouslySetInnerHTML={{ __html: content }}

        />
        <h2 className='text-[#1B1464] text-[24px] font-[500] mb-4'>Summary and action points Freddie (Farm Fields)</h2>

        <p className='text-[#1B1464] text-[16px] font-[300] mb-4'>Dear Freddie,</p>

        <p className='text-[#1B1464] text-[16px] font-[300] mb-4'>Thank you for our annual update meeting. Here's a summary of what we discussed, including points regarding the new potato slicing machine.</p>

        <h4 className='text-[#1B1464] text-[18px] font-[600] mb-2 mt-8'>Summary:</h4>
        <ul className='mb-4'>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">We talked about the impressive growth of Farm Fields and the significant decrease in the number of claims in the recent months.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">There was an outstanding harvest results discussed. It was nice to hear that it will be better yields.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">We then discussed the short cutoff from your 2024 to 2025 campaign, and I provided you with an update on the taxes.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">Regarding the new potato slicing machine, we discussed its value, compliance with regulations and potential discount for prompt decision. This would ultimately lead to a premium increase.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">Lastly, we discussed business options available that might ensure you with <strong>business interruption insurance</strong> and <strong>breakdown insurance</strong> for business continuity.</li>
        </ul>

        <h4 className='text-[#1B1464] text-[18px] font-[600] mb-2 mt-8'>Action points for you:</h4>
        <ul>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">It would be great if you could send me the invoice for the potato slicing machine within 3 business days after purchase.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">Take the time to review the proposals for additional insurances and let me know if there's anything else you need.</li>
        </ul>

        <h4 className='text-[#1B1464] text-[18px] font-[600] mb-2 mt-8'>Action points for me:</h4>
        <ul>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">Once I have received the invoice for the potato slicing machine, I will adjust the policy and calculate the new premium.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">I will send you an initial offer in 5 business days with the details of the proposed additional insurances.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">Add specific information on the specifics of the ongoing claim and keep you updated on the progress.</li>
          <li className="ml-6 list-disc text-[#1B1464] text-[16px] font-[300] mb-2">I will look into the possibilities of a premium discount when considering all insurances.</li>
        </ul>

        <p className='text-[#1B1464] text-[16px] font-[300] mb-4 mt-8'>Feel free to let me know if there are any further questions. I am ready to help you.</p>

        <p className='text-[#1B1464] text-[16px] font-[300] mb-4 mt-8'>Best regards,</p>

        <p className='text-[#1B1464] text-[16px] font-[300] mb-4 mt-8'>Agnes</p>
      </div>
    </div>
  );
};

export default SummaryContent;
