
import React from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Info, FileEdit, Share } from 'lucide-react';

interface SummaryContentProps {
  content: string;
  onEdit: () => void;
  onShare: () => void;
}

const SummaryContent: React.FC<SummaryContentProps> = ({
  content,
  onEdit,
  onShare
}) => {
  return (
    <Card className="h-full">
      <CardContent className="p-6">
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center text-sm text-gray-500">
            <Info className="h-4 w-4 mr-2" />
            <span>Generated by AI. Check for accuracy.</span>
          </div>
          <div className="flex space-x-3">
            <Button variant="outline" onClick={onEdit}>
              <FileEdit className="h-4 w-4 mr-2" />
              Edit summary
            </Button>
            <Button onClick={onShare}>
              <Share className="h-4 w-4 mr-2" />
              Share with client
            </Button>
          </div>
        </div>

        <div 
          className="prose max-w-none mb-6"
          dangerouslySetInnerHTML={{ __html: content }}
        />
      </CardContent>
    </Card>
  );
};

export default SummaryContent;
